addSbtPlugin("io.get-coursier" % "sbt-coursier"           % "1.0.1")
addSbtPlugin("com.geirsson"    % "sbt-scalafmt"           % "1.4.0")
addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"   % "sbt-scoverage"          % "1.5.1")
addSbtPlugin("com.github.sbt"  % "sbt-findbugs"           % "2.0.0")
