addSbtPlugin("com.geirsson"       % "sbt-scalafmt"           % "1.4.0")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "1.6.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"    % "1.6.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                % "0.3.7")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"        % "2.4.10")
