name: Publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1 (2025-11-17T15:57:55Z)
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9  # v4.8.0 (2025-12-04T03:00:25Z)
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Setup SBT
        uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd  # v1.1.14 (2025-10-05T20:19:35Z)
      - uses: olafurpg/setup-gpg@a62c5903e98d692e520bc2f46103b919a61dd386  # v3 (2020-10-19T16:15:15Z)
      - name: Publish To Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
